import { Provider } from '@/components/ui/provider'
import Footer from '@/features/Footer'
import { Header } from '@/features/Header'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import localfont from 'next/font/local'
import 'normalize.css'
import { authOptions } from './api/auth/[...nextauth]/authOptions'
import './globals.css'

const pretendard = localfont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})
export const metadata: Metadata = {
  title: 'Exit Mate',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html
      lang="ko"
      className={`${pretendard.variable}`}
      suppressHydrationWarning
    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className={pretendard.className}>
          <Provider session={session}>
            <Header />
            {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
